name: 'Skript Tests'
description: 'Runs Skript tests'
inputs:
  test-script-directory:
    description: 'The directory containing the tests to run'
    required: true
  skript-repo-ref:
    description: 'The Git reference of the Skript version to test with (this can be a commit sha, branch, tag, etc.)'
    required: false
  run-vanilla-tests:
    description: 'Controls whether or not the vanilla Skript tests are run. It is recommended you keep this on to ensure your addon doesn''t change vanilla behavior'
    required: false
    default: 'true'

outputs:
  passed:
    description: 'Whether or not the tests passed'

runs:
  using: 'docker'
  image: 'Dockerfile'
  args:
    - ${{ inputs.test-script-directory }}
    - ${{ inputs.skript-repo-ref }}
    - ${{ inputs.run-vanilla-tests }}
