name: Test action

on:
  - push
  - pull_request

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
        - name: Checkout repo
          uses: actions/checkout@v3
        - name: Build Dockerfile
          run: docker build . --file Dockerfile
        - name: Create custom test script
          run: |
            mkdir test-scripts
            printf 'test "github actions":\n\tassert true is true with "it worked!"' > test-scripts/actions.sk
        - name: Run skript-test-action with vanilla tests
          uses: ./
          with:
            test_script_directory: test-scripts
        - name: Run skript-test-action without vanilla tests
          uses: ./
          with:
            test_script_directory: test-scripts
            run_vanilla_tests: false
        - name: Run skript-test-action on tag with vanilla tests
          uses: ./
          with:
            test_script_directory: test-scripts
            skript_repo_ref: 2.8.2
        - name: Run skript-test-action on tag without vanilla tests
          uses: ./
          with:
            test_script_directory: test-scripts
            run_vanilla_tests: false
            skript_repo_ref: 2.8.2
